### Application Settings ###
spring.application.name=order-management
spring.data.rest.detection-strategy=annotated

### Server ###
server.port=8080

### Data Source ###
spring.datasource.url=jdbc:postgresql://213.109.146.52:5433/ordermanagement
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

### Security ###
token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

### Logging ###
logging.level.io.micrometer=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.actuate=DEBUG
logging.level.org.springframework.cache=DEBUG

### Metrics ###
management.endpoints.web.exposure.include=*
management.metrics.enable.http.server.requests=true
